# Generated by Django 3.1 on 2020-08-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices_app', '0002_product_price2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price2',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
