# Generated by Django 3.1 on 2020-08-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices_app', '0004_auto_20200807_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
