# Generated by Django 3.1 on 2020-08-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices_app', '0005_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
