# Generated by Django 3.1 on 2020-08-07 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prices_app', '0006_auto_20200807_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField(default=0)),
                ('url', models.CharField(max_length=200)),
                ('logo', models.CharField(max_length=200)),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='prices_app.product', verbose_name='Product')),
            ],
        ),
    ]
