# Generated by Django 3.1 on 2020-08-07 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices_app', '0007_productdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='product',
        ),
    ]
