# Generated by Django 3.1 on 2020-08-07 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prices_app', '0008_remove_productdetail_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='prices_app.product', verbose_name='Product'),
        ),
    ]
