# Generated by Django 3.1 on 2020-08-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices_app', '0009_productdetail_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='product',
        ),
        migrations.AddField(
            model_name='productdetail',
            name='product',
            field=models.ManyToManyField(default=1, to='prices_app.Product', verbose_name='Product'),
        ),
    ]
